# If DB_URL exists, use it. Otherwise, fallback directly to your live Aiven DB!
spring.datasource.url=${DB_URL:jdbc:mysql://spring-mysql-db-my-spring-db.g.aivencloud.com:18920/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${DB_USER:avnadmin}
spring.datasource.password=${DB_PASSWORD:AVNS_YcdRD-NZ9Uru0b2AbI0}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8081}